package com.izivia.ocpi.toolkit.modules.cdr.domain

enum class TokenType {
    /**
     * One time use Token ID generated by a server (or App.) The eMSP uses this to bind a Session to a
    customer, probably an app user
     */
    AD_HOC_USER,

    /**
     * Token ID generated by a server (or App.) to identify a user of an App. The same user uses the
    same Token for every Session.
     */

    APP_USER,

    /**
     * Other type of token
     */
    OTHER_,

    /**
     * RFID Token
     */
    RFID
}
