package com.izivia.ocpi.toolkit.modules.tokens.domain

/**
 * Note: The eMSP is RECOMMENDED to push Tokens with type: AD_HOC_USER or APP_USER with whitelist set to NEVER.
 * Whitelists are very useful for RFID type Tokens, but the AD_HOC_USER/APP_USER Tokens are used to start Sessions from
 * an App etc. so whitelisting them has no advantages.
 */
enum class TokenType {
    /**
     * One time use Token ID generated by a server (or App.) The eMSP uses this to bind a Session to a customer,
     * probably an app user.
     */
    AD_HOC_USER,

    /**
     * Token ID generated by a server (or App.) to identify a user of an App. The same user uses the same Token for
     * every Session.
     */
    APP_USER,

    /**
     * Other type of token
     */
    OTHER,

    /**
     * RFID Token
     */
    RFID,
}
