package com.izivia.ocpi.toolkit.modules.chargingProfiles.repositories

import com.izivia.ocpi.toolkit.modules.chargingProfiles.ChargingProfilesScspInterface

interface ChargingProfilesScspRepository : ChargingProfilesScspInterface
