package com.izivia.ocpi.toolkit.modules.chargingProfiles.services

import com.izivia.ocpi.toolkit.modules.chargingProfiles.ChargingProfilesCpoInterface

interface ChargingProfilesChargePointService : ChargingProfilesCpoInterface
